async function loadDetail() {
  const target = document.querySelector('#detail-content');
  try {
    const property = await CampusNestAPI.getProperty(new URLSearchParams(location.search).get('id')); const images = property.images || [];
    if (Auth.isStudent()) { try { await CampusNestAPI.getFavorites(); } catch {} }
    const favorite = CampusNestAPI.isFavoritedLocal(property.id);
    target.innerHTML = `<div class="detail-hero"><div><div class="gallery-main" style="background-image:url('${App.escapeHtml(images[0]?.public_url || images[0] || '')}')"></div></div><div class="detail-panel"><span class="eyebrow">Approved listing</span><h1>${App.escapeHtml(property.title)}</h1><p class="muted">${App.escapeHtml(property.university || '')} · ${App.escapeHtml(property.location || '')} · ${App.escapeHtml(property.area || '')}</p><div class="price">${App.formatNaira(property.price)} <small>/ ${App.escapeHtml(property.price_period || 'year')}</small></div><p>${App.escapeHtml(property.property_type)} · ${Number(property.bedrooms)} bedrooms · ${Number(property.bathrooms || 0)} bathrooms</p><div class="amenities">${(property.amenities || []).map((item) => `<span>${App.escapeHtml(item)}</span>`).join('')}</div><button class="btn" id="save-detail">${favorite ? '♥ Saved' : '♡ Save home'}</button><button class="btn" id="contact-agent">Contact Agent</button></div></div><section class="section"><div class="detail-panel"><h2>About this home</h2><p>${App.escapeHtml(property.description || 'No description provided.')}</p><p class="muted">Listed by ${App.escapeHtml(property.owner_name || 'CampusNest member')} · ${App.escapeHtml(property.availability || 'available')}</p></div></section>`;
    document.querySelector('#save-detail').onclick = async () => { if (!Auth.isLoggedIn()) return App.showToast('Log in to save homes', 'error'); try { const result = await CampusNestAPI.toggleFavorite(property.id); document.querySelector('#save-detail').textContent = result.favorited ? '♥ Saved' : '♡ Save home'; App.showToast(result.favorited ? 'Saved to your favorites' : 'Removed from your favorites'); } catch (error) { App.showToast(error.message, 'error'); } };
    document.querySelector('#contact-agent').onclick = async () => { if (!Auth.isLoggedIn()) return App.showToast('Log in to contact the agent', 'error'); if (!Auth.isStudent()) return App.showToast('Only students can contact an agent from a listing', 'error'); const message = window.prompt('Write a message to the agent'); if (!message?.trim()) return; try { await CampusNestAPI.sendMessage(property.id, message); App.showToast('Message sent'); } catch (error) { App.showToast(error.message, 'error'); } };
  } catch { target.innerHTML = '<div class="empty">Property not found or no longer available.</div>'; }
}
document.addEventListener('DOMContentLoaded', () => { if (document.querySelector('#detail-content')) loadDetail(); });
