async function loadBrowse() {
	const grid = document.querySelector('#property-grid'); const form = document.querySelector('#filters'); const params = new URLSearchParams(location.search); let page = Number(params.get('page') || 1);
	for (const [key, value] of params) { const field = form.elements[key]; if (field) field.value = value; }
	const preset = document.querySelector('#price-preset'); const active = document.querySelector('#active-filters'); const pagination = document.querySelector('#pagination');
	const clear = () => { form.reset(); preset.value = ''; page = 1; run(); };
	const renderActive = (values) => { active.innerHTML = Object.entries(values).filter(([key, value]) => value && key !== 'sort' && key !== 'page' && key !== 'limit').map(([key, value]) => `<button type="button" class="filter-chip" data-clear-filter="${App.escapeHtml(key)}">${App.escapeHtml(key === 'minPrice' ? '₦' + Number(value).toLocaleString('en-NG') + '+' : key === 'maxPrice' ? '₦' + Number(value).toLocaleString('en-NG') + ' max' : value)} ×</button>`).join(''); active.querySelectorAll('[data-clear-filter]').forEach((button) => button.onclick = () => { form.elements[button.dataset.clearFilter].value = ''; page = 1; run(); }); };
	const run = async () => { const values = Object.fromEntries(new FormData(form)); if (Number(values.minPrice) < 0 || Number(values.maxPrice) < 0 || (values.minPrice && values.maxPrice && Number(values.maxPrice) < Number(values.minPrice))) { grid.innerHTML = '<div class="empty">Enter a valid price range.</div>'; return; } values.page = page; values.limit = 12; history.replaceState(null, '', `${location.pathname}?${new URLSearchParams(Object.entries(values).filter(([, value]) => value))}`); renderActive(values); grid.innerHTML = '<div class="empty">Loading homes...</div>'; try { const data = await CampusNestAPI.getProperties(values); grid.innerHTML = data.length ? data.map(propertyCard).join('') : '<div class="empty"><h2>No properties found</h2><p>Try adjusting your filters or expanding your price range.</p><button type="button" class="btn" id="empty-clear">Clear filters</button></div>'; wireFavorites(grid); const meta = data.pagination || {}; pagination.innerHTML = meta.totalPages > 1 ? `<button type="button" class="btn" id="previous-page" ${meta.page <= 1 ? 'disabled' : ''}>Previous</button> Page ${meta.page} of ${meta.totalPages} (${meta.total} results) <button type="button" class="btn" id="next-page" ${meta.page >= meta.totalPages ? 'disabled' : ''}>Next</button>` : meta.total ? `${meta.total} result${meta.total === 1 ? '' : 's'}` : ''; document.querySelector('#empty-clear')?.addEventListener('click', clear); document.querySelector('#previous-page')?.addEventListener('click', () => { page -= 1; run(); }); document.querySelector('#next-page')?.addEventListener('click', () => { page += 1; run(); }); } catch (error) { grid.innerHTML = `<div class="empty">${App.escapeHtml(error.message)}</div>`; } };
	preset.onchange = () => { const [min, max] = preset.value.split('-'); form.elements.minPrice.value = min || ''; form.elements.maxPrice.value = max || ''; page = 1; run(); };
	form.oninput = () => { page = 1; run(); }; document.querySelector('#clear-filters').onclick = clear;
	await Auth.whenReady(); if (Auth.isStudent()) { try { await CampusNestAPI.getFavorites(); } catch {} } await run();
}
document.addEventListener('DOMContentLoaded', () => { if (document.querySelector('#property-grid')) loadBrowse(); });