const express = require('express');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

const app = express();
const cors = require('cors');
app.use(cors({ origin: 'https://campusnest.space' }));
app.use((req, res, next) => { console.log(new Date().toISOString(), req.method, req.url); next(); });
app.use(express.json());
app.use(express.static(path.join(__dirname)));
const supabaseUrl = process.env.SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const supabase = supabaseUrl && serviceKey ? createClient(supabaseUrl, serviceKey) : null;
const requireSupabase = (res) => { if (!supabase) { res.status(503).json({ error: 'Authentication service is not configured' }); return false; } return true; };

async function authenticateUser(req, res, next) {
  const token = (req.headers.authorization || '').replace(/^Bearer\s+/i, '');
  if (!token) return res.status(401).json({ error: 'Authentication required' });
  if (requireSupabase(res)) return;
  const { data, error } = await supabase.auth.getUser(token);
  if (error || !data.user) return res.status(401).json({ error: 'Authentication required' });
  const { data: profile, error: profileError } = await supabase.from('profiles').select('*').eq('id', data.user.id).single();
  if (profileError || !profile) {
    if (req.method === 'POST' && req.path === '/api/users/profile') { req.authUser = data.user; req.user = {}; return next(); }
    return res.status(403).json({ error: 'User profile is missing' });
  }
  req.authUser = data.user; req.user = profile; next();
}
const requireRole = (role) => (req, res, next) => req.user.role === role ? next() : res.status(403).json({ error: 'Forbidden' });
const requireStudent = requireRole('student');
const requireLandlord = requireRole('landlord');
const requireAgent = requireRole('agent');
const requireAdmin = requireRole('admin');
const requirePropertyOwner = (req, res, next) => ['landlord', 'agent'].includes(req.user.role) ? next() : res.status(403).json({ error: 'Only landlords and agents can manage properties' });
const publicProfile = ({ id, name, email, phone, university, role, created_at }) => ({ id, name, email, phone, university, role, created_at });
async function getRows(table, filters = {}) { let query = supabase.from(table).select('*'); for (const [key, value] of Object.entries(filters)) query = query.eq(key, value); const { data, error } = await query; if (error) throw error; return data; }
const propertySelect = 'id,title,description,price,price_period,university,location,area,property_type,bedrooms,bathrooms,amenities,availability,approval_status,owner_id,owner_name,created_at';
function parsePrice(value, label) { if (value === undefined || value === '') return null; const parsed = Number(value); if (!Number.isFinite(parsed) || parsed < 0) throw new Error(`${label} must be a valid non-negative number`); return parsed; }
function parsePositiveInt(value, label, fallback) { if (value === undefined || value === '') return fallback; const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < 1) throw new Error(`${label} must be a positive integer`); return parsed; }
async function attachImages(rows) { if (!rows.length) return []; const { data, error } = await supabase.from('property_images').select('id,property_id,public_url,sort_order').in('property_id', rows.map((row) => row.id)).order('sort_order'); if (error) throw error; return rows.map((property) => ({ ...property, images: (data || []).filter((image) => image.property_id === property.id) })); }

app.post('/api/users/register', (req, res) => { if (!requireSupabase(res)) return; const { name, email, password, role } = req.body || {}; if (!name || !email || !password || !['student', 'landlord', 'agent'].includes(role)) return res.status(400).json({ error: 'Name, email, password and a valid account type are required' }); res.status(400).json({ error: 'Register through the Supabase client' }); });
app.post('/api/users/login', (req, res) => res.status(400).json({ error: 'Log in through the Supabase client' }));
async function withImages(rows) { return attachImages(rows); }
app.get('/api/properties', async (req, res) => { if (!requireSupabase(res)) return; try {
  const { search, q, university, location, propertyType, property_type: legacyType, bedrooms, availability, sort = 'newest' } = req.query;
  const minPrice = parsePrice(req.query.minPrice, 'Minimum price'); const maxPrice = parsePrice(req.query.maxPrice, 'Maximum price');
  if (minPrice !== null && maxPrice !== null && maxPrice < minPrice) return res.status(400).json({ error: 'Maximum price cannot be less than minimum price' });
  const page = parsePositiveInt(req.query.page, 'Page', 1); const limit = Math.min(parsePositiveInt(req.query.limit, 'Limit', 12), 50);
  const queryText = search || q; if (bedrooms !== undefined && bedrooms !== '' && (!Number.isInteger(Number(bedrooms)) || Number(bedrooms) < 0)) throw new Error('Bedrooms must be a non-negative integer'); let query = supabase.from('properties').select(propertySelect, { count: 'exact' }).eq('approval_status', 'approved');
  if (university) query = query.ilike('university', `%${university}%`); if (location) query = query.ilike('location', `%${location}%`); if (propertyType || legacyType) query = query.eq('property_type', propertyType || legacyType);
  if (bedrooms !== undefined && bedrooms !== '') query = query.eq('bedrooms', Number(bedrooms)); if (availability) query = query.eq('availability', availability); if (minPrice !== null) query = query.gte('price', minPrice); if (maxPrice !== null) query = query.lte('price', maxPrice);
  if (queryText) { const safeText = String(queryText).replace(/[,%()]/g, ' ').trim(); if (safeText) query = query.or(`title.ilike.%${safeText}%,location.ilike.%${safeText}%,area.ilike.%${safeText}%,university.ilike.%${safeText}%`); }
  if (!['newest', 'price_asc', 'price_desc'].includes(sort)) return res.status(400).json({ error: 'Invalid sort option' });
  query = query.order(sort === 'newest' ? 'created_at' : 'price', { ascending: sort !== 'price_desc' }).range((page - 1) * limit, page * limit - 1); const { data, error, count } = await query; if (error) throw error;
  res.json({ properties: await attachImages(data || []), pagination: { page, limit, total: count || 0, totalPages: Math.ceil((count || 0) / limit) } });
} catch (error) { res.status(400).json({ error: error.message || 'Unable to load properties' }); } });
app.get('/api/properties/:id', async (req, res) => { if (!requireSupabase(res)) return; try { let rows = await getRows('properties', { id: req.params.id, approval_status: 'approved' }); const token = (req.headers.authorization || '').replace(/^Bearer\s+/i, ''); if (!rows.length && token) { const { data } = await supabase.auth.getUser(token); if (data.user) rows = await getRows('properties', { id: req.params.id, owner_id: data.user.id }); } const result = await withImages(rows); result[0] ? res.json(result[0]) : res.status(404).json({ error: 'Property not found' }); } catch { res.status(500).json({ error: 'Unable to load property' }); } });
app.get('/api/users/profile', authenticateUser, (req, res) => res.json(publicProfile(req.user)));
app.get('/api/profile', authenticateUser, (req, res) => res.json(publicProfile(req.user)));
app.post('/api/users/profile', authenticateUser, async (req, res) => {
  const { name, email, phone, university, role } = req.body || {};
  if (!name || !['student', 'landlord', 'agent'].includes(role)) return res.status(400).json({ error: 'A name and valid account type are required' });
  const { data, error } = await supabase.from('profiles').insert({ id: req.authUser.id, name, email: email || req.authUser.email, phone, university, role }).select('*').single();
  if (error) return res.status(error.code === '23505' ? 409 : 500).json({ error: error.code === '23505' ? 'Profile already exists' : 'Unable to create profile' });
  res.status(201).json(publicProfile(data));
});
async function updateProfile(req, res) { const { email } = req.body || {}; if (email !== undefined && !/^\S+@\S+\.\S+$/.test(email)) return res.status(400).json({ error: 'Enter a valid email address' }); const updates = {}; for (const field of ['name', 'email', 'phone', 'university']) if (req.body[field] !== undefined) updates[field] = String(req.body[field]).trim(); if (!updates.name) return res.status(400).json({ error: 'Name is required' }); try { if (updates.email && updates.email !== req.user.email) { const result = await supabase.auth.admin.updateUserById(req.authUser.id, { email: updates.email }); if (result.error) return res.status(409).json({ error: 'Email is already in use or could not be updated' }); } const { data, error } = await supabase.from('profiles').update(updates).eq('id', req.authUser.id).select('*').single(); if (error) throw error; res.json(publicProfile(data)); } catch { res.status(500).json({ error: 'Unable to update profile' }); } }
app.patch('/api/users/profile', authenticateUser, updateProfile);
app.patch('/api/profile', authenticateUser, updateProfile);
const propertyTypes = ['Self-contained', 'Single room', 'Room and parlour', 'Shared apartment', 'Flat', 'Hostel'];
function validateProperty(body) {
  const required = ['title', 'price', 'price_period', 'university', 'location', 'area', 'property_type', 'bedrooms', 'bathrooms', 'availability'];
  if (required.some((field) => body[field] === undefined || body[field] === '')) return 'Complete all required property fields';
  if (!propertyTypes.includes(body.property_type)) return 'Invalid property type';
  if (!Number.isFinite(Number(body.price)) || Number(body.price) <= 0 || !Number.isInteger(Number(body.bedrooms)) || Number(body.bedrooms) < 0 || !Number.isInteger(Number(body.bathrooms)) || Number(body.bathrooms) < 0) return 'Price, bedrooms and bathrooms must be valid positive numbers';
  if (!['year', 'month', 'week'].includes(body.price_period) || !['available', 'unavailable'].includes(body.availability)) return 'Invalid price period or availability';
  return null;
}
const propertyFields = ['title', 'description', 'price', 'price_period', 'university', 'location', 'area', 'property_type', 'bedrooms', 'bathrooms', 'amenities', 'availability'];
const propertyPayload = (body) => Object.fromEntries(propertyFields.filter((field) => body[field] !== undefined).map((field) => [field, ['price', 'bedrooms', 'bathrooms'].includes(field) ? Number(body[field]) : body[field]]));
app.post('/api/properties', authenticateUser, requirePropertyOwner, async (req, res) => { const invalid = validateProperty(req.body || {}); if (invalid) return res.status(400).json({ error: invalid }); try { const payload = { ...propertyPayload(req.body), owner_id: req.authUser.id, owner_name: req.user.name, verification_status: 'pending', approval_status: 'pending' }; const { data, error } = await supabase.from('properties').insert(payload).select().single(); if (error) throw error; res.status(201).json(data); } catch { res.status(500).json({ error: 'Unable to create property' }); } });
async function ownerListings(userId) { const rows = await getRows('properties', { owner_id: userId }); const images = rows.length ? (await supabase.from('property_images').select('*').in('property_id', rows.map((p) => p.id))).data || [] : []; return rows.map((p) => ({ ...p, images: images.filter((image) => image.property_id === p.id).sort((a, b) => a.sort_order - b.sort_order) })); }
app.get('/api/my/properties', authenticateUser, requirePropertyOwner, async (req, res) => { try { res.json(await ownerListings(req.authUser.id)); } catch { res.status(500).json({ error: 'Unable to load listings' }); } });
app.get('/api/properties/mine', authenticateUser, requirePropertyOwner, async (req, res) => { try { res.json(await ownerListings(req.authUser.id)); } catch { res.status(500).json({ error: 'Unable to load listings' }); } });
app.put('/api/properties/:id', authenticateUser, requirePropertyOwner, async (req, res) => { const invalid = validateProperty(req.body || {}); if (invalid) return res.status(400).json({ error: invalid }); try { const { data, error } = await supabase.from('properties').update({ ...propertyPayload(req.body), approval_status: 'pending', verification_status: 'pending' }).eq('id', req.params.id).eq('owner_id', req.authUser.id).select().single(); if (error || !data) return res.status(404).json({ error: 'Property not found' }); res.json(data); } catch { res.status(500).json({ error: 'Unable to update property' }); } });
app.delete('/api/properties/:id', authenticateUser, requirePropertyOwner, async (req, res) => { try { const { data, error } = await supabase.from('properties').delete().eq('id', req.params.id).eq('owner_id', req.authUser.id).select('id'); if (error) throw error; if (!data.length) return res.status(404).json({ error: 'Property not found' }); res.json({ success: true }); } catch { res.status(500).json({ error: 'Unable to delete property' }); } });
app.get('/api/properties/:id/images', authenticateUser, requirePropertyOwner, async (req, res) => { try { const properties = await getRows('properties', { id: req.params.id, owner_id: req.authUser.id }); if (!properties.length) return res.status(404).json({ error: 'Property not found' }); res.json(await getRows('property_images', { property_id: req.params.id, owner_id: req.authUser.id })); } catch { res.status(500).json({ error: 'Unable to load images' }); } });
app.post('/api/properties/:id/images', authenticateUser, requirePropertyOwner, async (req, res) => { const { storage_path, public_url, sort_order = 0 } = req.body || {}; if (!storage_path || !public_url) return res.status(400).json({ error: 'Image metadata is required' }); try { const properties = await getRows('properties', { id: req.params.id, owner_id: req.authUser.id }); if (!properties.length) return res.status(404).json({ error: 'Property not found' }); const { data, error } = await supabase.from('property_images').insert({ property_id: req.params.id, owner_id: req.authUser.id, storage_path, public_url, sort_order: Number(sort_order) }).select().single(); if (error) throw error; res.status(201).json(data); } catch { res.status(500).json({ error: 'Unable to save image' }); } });
app.delete('/api/properties/:propertyId/images/:imageId', authenticateUser, requirePropertyOwner, async (req, res) => { try { const properties = await getRows('properties', { id: req.params.propertyId, owner_id: req.authUser.id }); if (!properties.length) return res.status(404).json({ error: 'Property not found' }); const { data, error } = await supabase.from('property_images').delete().eq('id', req.params.imageId).eq('property_id', req.params.propertyId).eq('owner_id', req.authUser.id).select('storage_path'); if (error) throw error; if (!data.length) return res.status(404).json({ error: 'Image not found' }); await supabase.storage.from('property-images').remove([data[0].storage_path]); res.json({ success: true }); } catch { res.status(500).json({ error: 'Unable to delete image' }); } });
async function adminProperties(status) { const query = supabase.from('properties').select(`${propertySelect},property_images(id,public_url,sort_order)`).eq('approval_status', status).order('created_at', { ascending: false }); const { data, error } = await query; if (error) throw error; return data || []; }
app.get('/api/admin/stats', authenticateUser, requireAdmin, async (req, res) => { try { const [{ data: profiles, error: profilesError }, { data: properties, error: propertiesError }, { count: pendingReports, error: reportsError }] = await Promise.all([supabase.from('profiles').select('role'), supabase.from('properties').select('approval_status'), supabase.from('property_reports').select('id', { count: 'exact', head: true }).eq('status', 'pending')]); if (profilesError || propertiesError || reportsError) throw profilesError || propertiesError || reportsError; const countRole = (role) => (profiles || []).filter((profile) => profile.role === role).length; const countStatus = (status) => (properties || []).filter((property) => property.approval_status === status).length; res.json({ totalUsers: profiles?.length || 0, students: countRole('student'), landlords: countRole('landlord'), agents: countRole('agent'), totalProperties: properties?.length || 0, pendingProperties: countStatus('pending'), approvedProperties: countStatus('approved'), rejectedProperties: countStatus('rejected'), removedProperties: countStatus('removed'), pendingReports: pendingReports || 0 }); } catch { res.status(500).json({ error: 'Unable to load admin statistics' }); } });
app.get('/api/admin/users', authenticateUser, requireAdmin, async (req, res) => { try { const { data, error } = await supabase.from('profiles').select('id,name,email,role,university,created_at').order('created_at', { ascending: false }); if (error) throw error; res.json(data || []); } catch { res.status(500).json({ error: 'Unable to load users' }); } });
app.get('/api/admin/properties', authenticateUser, requireAdmin, async (req, res) => { try { const status = req.query.status || 'pending'; if (!['pending', 'approved', 'rejected', 'removed'].includes(status)) return res.status(400).json({ error: 'Invalid property status' }); res.json(await adminProperties(status)); } catch { res.status(500).json({ error: 'Unable to load properties' }); } });
app.get('/api/admin/properties/pending', authenticateUser, requireAdmin, async (req, res) => { try { res.json(await adminProperties('pending')); } catch { res.status(500).json({ error: 'Unable to load pending properties' }); } });
async function moderateProperty(req, res, status) { const reason = String(req.body?.reason || req.body?.rejection_reason || '').trim(); if (status === 'rejected' && !reason) return res.status(400).json({ error: 'A rejection reason is required' }); try { const updates = { approval_status: status, verification_status: status === 'approved' ? 'verified' : 'rejected', rejection_reason: status === 'rejected' ? reason : null }; const { data, error } = await supabase.from('properties').update(updates).eq('id', req.params.id).select(propertySelect).single(); if (error || !data) return res.status(404).json({ error: 'Property not found' }); res.json(data); } catch { res.status(500).json({ error: 'Unable to update property status' }); } }
app.patch('/api/admin/properties/:id/approve', authenticateUser, requireAdmin, (req, res) => moderateProperty(req, res, 'approved'));
app.patch('/api/admin/properties/:id/reject', authenticateUser, requireAdmin, (req, res) => moderateProperty(req, res, 'rejected'));
app.patch('/api/admin/properties/:id/remove', authenticateUser, requireAdmin, (req, res) => moderateProperty(req, res, 'removed'));
app.patch('/api/admin/properties/:id', authenticateUser, requireAdmin, async (req, res) => { const status = req.body?.approval_status; if (!['approved', 'rejected', 'removed'].includes(status)) return res.status(400).json({ error: 'Invalid moderation status' }); return moderateProperty(req, res, status); });
app.get('/api/admin/reports', authenticateUser, requireAdmin, async (req, res) => { try { const status = req.query.status || 'pending'; if (!['pending', 'reviewed', 'resolved', 'dismissed'].includes(status)) return res.status(400).json({ error: 'Invalid report status' }); const { data, error } = await supabase.from('property_reports').select('*,properties(id,title,location),profiles!property_reports_reporter_id_fkey(name,email)').eq('status', status).order('created_at', { ascending: false }); if (error) throw error; res.json(data || []); } catch { res.status(500).json({ error: 'Unable to load reports' }); } });
app.patch('/api/admin/reports/:id/:action', authenticateUser, requireAdmin, async (req, res) => { const status = req.params.action; if (!['reviewed', 'resolved', 'dismissed'].includes(status)) return res.status(400).json({ error: 'Invalid report action' }); try { const { data, error } = await supabase.from('property_reports').update({ status, reviewed_by: req.authUser.id, reviewed_at: new Date().toISOString() }).eq('id', req.params.id).select().single(); if (error || !data) return res.status(404).json({ error: 'Report not found' }); res.json(data); } catch { res.status(500).json({ error: 'Unable to update report' }); } });
app.post('/api/properties/:id/reports', authenticateUser, async (req, res) => { const reason = String(req.body?.reason || '').trim(); const description = String(req.body?.description || '').trim(); if (!reason || !description) return res.status(400).json({ error: 'Report reason and description are required' }); try { const { data: property, error: propertyError } = await supabase.from('properties').select('id').eq('id', req.params.id).eq('approval_status', 'approved').maybeSingle(); if (propertyError) throw propertyError; if (!property) return res.status(404).json({ error: 'Property not found' }); const { data, error } = await supabase.from('property_reports').insert({ property_id: property.id, reporter_id: req.authUser.id, reason, description }).select().single(); if (error) throw error; res.status(201).json(data); } catch { res.status(500).json({ error: 'Unable to submit report' }); } });
app.get('/api/favorites', authenticateUser, requireStudent, async (req, res) => { try { const { data, error } = await supabase.from('favorites').select('property_id, created_at').eq('user_id', req.authUser.id).order('created_at', { ascending: false }); if (error) throw error; const ids = (data || []).map((favorite) => favorite.property_id); const properties = ids.length ? await supabase.from('properties').select(propertySelect).in('id', ids).eq('approval_status', 'approved') : { data: [] }; if (properties.error) throw properties.error; res.json(await attachImages(properties.data || [])); } catch { res.status(500).json({ error: 'Unable to load saved homes' }); } });
app.post('/api/favorites/:id', authenticateUser, requireStudent, async (req, res) => { try { const property = await supabase.from('properties').select('id').eq('id', req.params.id).eq('approval_status', 'approved').maybeSingle(); if (property.error) throw property.error; if (!property.data) return res.status(404).json({ error: 'Property not found' }); const { data, error } = await supabase.from('favorites').upsert({ user_id: req.authUser.id, property_id: req.params.id }, { onConflict: 'user_id,property_id', ignoreDuplicates: true }).select().single(); if (error) throw error; res.status(201).json({ favorited: true, favorite: data }); } catch { res.status(500).json({ error: 'Unable to save home' }); } });
app.delete('/api/favorites/:id', authenticateUser, requireStudent, async (req, res) => { try { const { error } = await supabase.from('favorites').delete().eq('user_id', req.authUser.id).eq('property_id', req.params.id); if (error) throw error; res.json({ favorited: false }); } catch { res.status(500).json({ error: 'Unable to remove saved home' }); } });

app.get('/api/messages', authenticateUser, async (req, res) => { try { const { data, error } = await supabase.from('messages').select('*').or(`sender_id.eq.${req.authUser.id},receiver_id.eq.${req.authUser.id}`).order('created_at', { ascending: false }); if (error) throw error; const messages = data || []; const profileIds = [...new Set(messages.flatMap((item) => [item.sender_id, item.receiver_id]))]; const propertyIds = [...new Set(messages.map((item) => item.property_id))]; const profiles = profileIds.length ? await supabase.from('profiles').select('id,name').in('id', profileIds) : { data: [] }; const properties = propertyIds.length ? await supabase.from('properties').select('id,title').in('id', propertyIds) : { data: [] }; if (profiles.error || properties.error) throw profiles.error || properties.error; const names = Object.fromEntries((profiles.data || []).map((profile) => [profile.id, profile.name])); const titles = Object.fromEntries((properties.data || []).map((property) => [property.id, property.title])); res.json(messages.map((item) => ({ ...item, sender_name: names[item.sender_id] || 'CampusNest member', receiver_name: names[item.receiver_id] || 'CampusNest member', property_title: titles[item.property_id] || 'Property' }))); } catch { res.status(500).json({ error: 'Unable to load messages' }); } });
app.post('/api/messages', authenticateUser, async (req, res) => { const message = String(req.body?.message || '').trim(); const propertyId = req.body?.propertyId || req.body?.property_id; if (!message) return res.status(400).json({ error: 'Message cannot be empty' }); if (message.length > 2000) return res.status(400).json({ error: 'Message is too long' }); if (!propertyId) return res.status(400).json({ error: 'A property is required' }); try { const { data: property, error: propertyError } = await supabase.from('properties').select('id,owner_id').eq('id', propertyId).eq('approval_status', 'approved').maybeSingle(); if (propertyError) throw propertyError; if (!property) return res.status(404).json({ error: 'Property not found' }); if (property.owner_id === req.authUser.id) return res.status(400).json({ error: 'You cannot message yourself' }); const { data, error } = await supabase.from('messages').insert({ sender_id: req.authUser.id, receiver_id: property.owner_id, property_id: property.id, message }).select().single(); if (error) throw error; res.status(201).json(data); } catch { res.status(500).json({ error: 'Unable to send message' }); } });
app.patch('/api/messages/:id/read', authenticateUser, async (req, res) => { try { const { data, error } = await supabase.from('messages').update({ read_at: new Date().toISOString() }).eq('id', req.params.id).eq('receiver_id', req.authUser.id).is('read_at', null).select().single(); if (error || !data) return res.status(404).json({ error: 'Message not found' }); res.json(data); } catch { res.status(500).json({ error: 'Unable to mark message as read' }); } });
app.post('/api/users/password-reset-request', (req, res) => res.status(400).json({ error: 'Use the Supabase password reset flow' }));
app.post('/api/users/password-reset', (req, res) => res.status(400).json({ error: 'Use the Supabase password reset flow' }));
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));
const port = process.env.PORT || 3000; if (require.main === module) app.listen(port, () => console.log(`CampusNest running at http://localhost:${port}`));
module.exports = { app, authenticateUser, requireStudent, requireLandlord, requireAgent, requireAdmin };